# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set environment variables
        run: echo "${{ secrets.DOTENV }}" > .env
      - name: cleanup previous deploy
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            docker compose down
            rm -rf /home/ubuntu/code/nerif
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
            # Private Key
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            # Remote host
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            # Remote user
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            # Source directory
            SOURCE: "."
            # Target directory
            TARGET: "/home/ubuntu/code/nerif"
            # Arguments to pass to rsync
            # ARGS: # optional, default is -rltgoDzvO
            # An array of folder to exclude
            # EXCLUDE: # optional, default is
      - name: cleanup previous deploy
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd /home/ubuntu/code/nerif
            docker compose up --build
